# Generated by Django 5.1.3 on 2024-11-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abogado',
            name='contrasena',
            field=models.CharField(default=12345678, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default=1234567, max_length=128),
            preserve_default=False,
        ),
    ]
