# Generated by Django 5.1.3 on 2024-11-15 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_abogado_contrasena_usuario_contrasena'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abogado',
            old_name='contrasena',
            new_name='contrasena_abogado',
        ),
        migrations.RenameField(
            model_name='abogado',
            old_name='correo',
            new_name='correo_abogado',
        ),
        migrations.RenameField(
            model_name='abogado',
            old_name='documento',
            new_name='documento_abogado',
        ),
        migrations.RenameField(
            model_name='abogado',
            old_name='fecha_registro',
            new_name='fecha_registro_abogado',
        ),
        migrations.RenameField(
            model_name='abogado',
            old_name='nombre',
            new_name='nombre_abogado',
        ),
        migrations.RenameField(
            model_name='abogado',
            old_name='telefono',
            new_name='telefono_abogado',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='contrasena',
            new_name='contrasena_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='correo',
            new_name='correo_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='direccion',
            new_name='direccion_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='fecha_registro',
            new_name='fecha_registro_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='nombre_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='telefono',
            new_name='telefono_usuario',
        ),
    ]
