# Generated by Django 5.1.3 on 2024-11-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_contrasena_usuario_usuario_contrasena_usuarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
